### ISSUE TITLE
Audio data with multichannel

### ISSUE THREAD

**Issue by asurance** [aeroheim/audio-file-decoder#3]
I noticed that function `read_samples` in `/src/module/audio-decode.cpp` reads data in every channel and stores their average. Why not just store their raw value?

**Comment by aeroheim** [comment]
Yeah, it's mentioned in the caveats. The channels are downmixed for convenience since I primarily use the library for single channel audio analysis.

If you need the raw data of all channels I can probably make the changes. Changes should be fairly straight-forward, although my bandwidth is limited right now so I won't be able to get to it until sometime later.

**Comment by asurance** [comment]
Thank you very much. Actually, I tried to fixed this problem by myself (According to my understanding, I just need to push value into `dest` one by one). But I failed to compile `wasm` for not familiar with `Emscripten`. If it's convenient for you, can you help me with fixing [my fork](https://github.com/asurance/audio-file-decoder/actions)  or just provide an action to compile wasm and export it by uploading artifact.

**Comment by aeroheim** [comment]
I'll try to get around to it sometime this month hopefully! I've been meaning to revisit the build process to try and get it fully automated since dealing with emscripten is pretty painful.

**Comment by asurance** [comment]
OK, anyway, thank you very much.

**Comment by marcusstenbeck** [comment]
@aeroheim Did you ever get a chance to have a look at this? I'm hoping to use this to get stereo data.

**Comment by aeroheim** [comment]
Sorry for the delay. I just fixed some issues with the build and will be working on this now.

**Comment by aeroheim** [comment]
I've added support for this now in v2.3.0. You can check the readme to see how to get data from multiple channels.

If there are any issues with this feel free to re-open the issue.

**Comment by marcusstenbeck** [comment]
Much appreciated!

**Comment by bossesand** [comment]
Just a naive question, can this be used to be incuded in a webbplatser to decode 16 channels of AAC ?
I want to use it in webpage that can play without dowloading the complete file and also decode 16 channels aac on all platforms.
It needs to start play back immidiately when downloading a file with dash.js.
We have an ambisonic headtracked binaural player but it needs to be able to play +600MB files,
You can take a look at https://www.ohti.xyz/2021/original.html

**Comment by aeroheim** [comment]
@bossesand No worries!

> Just a naive question, can this be used to be incuded in a webbplatser to decode 16 channels of AAC ?

Yes, this is supported.

> I want to use it in webpage that can play without dowloading the complete file and also decode 16 channels aac on all platforms.
It needs to start play back immidiately when downloading a file with dash.js.
We have an ambisonic headtracked binaural player but it needs to be able to play +600MB files,

Decoding partial/incomplete files isn't supported. This library only works with complete file data, so you will need to download them first before decoding.

**Comment by bossesand** [comment]
Thank you for your feedback.
Happy New Year
